// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyA1REpp5InONSVM3VfHYLqdTaco-uvFrnE",
  appId: "1:700939221316:web:6c6c8490450813983b3f11",
  messagingSenderId: "700939221316",
  projectId: "flutter-pro-798d2",
  authDomain: "flutter-pro-798d2.firebaseapp.com",
  storageBucket: "flutter-pro-798d2.appspot.com", // critical fix
  measurementId: "G-FGFBWHLX5P",
);


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP2KrZ7HLbZHHeLVeYBMSA1zAQP9q1Wqs',
    appId: '1:700939221316:android:70f566651c34e59b3b3f11',
    messagingSenderId: '700939221316',
    projectId: 'flutter-pro-798d2',
    storageBucket: 'flutter-pro-798d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9nGBHI9Ve_IbdkNNYSzTCF9qDVPdkv60',
    appId: '1:700939221316:ios:d5aced634add19903b3f11',
    messagingSenderId: '700939221316',
    projectId: 'flutter-pro-798d2',
    storageBucket: 'flutter-pro-798d2.firebasestorage.app',
    iosBundleId: 'com.example.portfolioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9nGBHI9Ve_IbdkNNYSzTCF9qDVPdkv60',
    appId: '1:700939221316:ios:d5aced634add19903b3f11',
    messagingSenderId: '700939221316',
    projectId: 'flutter-pro-798d2',
    storageBucket: 'flutter-pro-798d2.firebasestorage.app',
    iosBundleId: 'com.example.portfolioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1REpp5InONSVM3VfHYLqdTaco-uvFrnE',
    appId: '1:700939221316:web:f7b7e964e808d6963b3f11',
    messagingSenderId: '700939221316',
    projectId: 'flutter-pro-798d2',
    authDomain: 'flutter-pro-798d2.firebaseapp.com',
    storageBucket: 'flutter-pro-798d2.firebasestorage.app',
    measurementId: 'G-CK4GPD8RH6',
  );
}
